nelmio_cors:
  defaults:
    origin_regex: true
    allow_origin: [ '^http://zavrsni.udruga-liberato.hr:[0-9]+' ]
    allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
    allow_headers: ['Content-Type', 'Authorization', 'username', 'password']
    expose_headers: ['Link']
    max_age: 3600
  paths:
    '^/': ~ 
