<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVN4nZJI\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVN4nZJI/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerVN4nZJI.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerVN4nZJI\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerVN4nZJI\App_KernelProdContainer([
    'container.build_hash' => 'VN4nZJI',
    'container.build_id' => '12cabc3a',
    'container.build_time' => 1615929210,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVN4nZJI');
